In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
mono_data = pd.read_csv('../data/mono.csv')
multi_data  = pd.read_csv('../data/multi.csv')

In [17]:
def clean_data(data):
    to_drop = ['Number', 'Sample number', 'Sample collection date', 'Name', 'Birth date', 'First PD date', 'End date', 'Height', 'Weight', 'CVD category', 'P']
    data = data.drop(to_drop, axis=1)
    return(data)

clean_mono_data = clean_data(mono_data)
clean_multi_data = clean_data(multi_data)

In [18]:
common_columns = list(set(clean_mono_data.columns) & set(clean_multi_data.columns))
clean_mono_data = clean_mono_data[common_columns]
clean_multi_data = clean_multi_data[common_columns]

In [19]:
clean_mono_data

,Diabetes,iPTH,NT-proBNP,TSAT,GA,ALB,LVEDD,SCR,TB,Age,...,FIB,ALT,AST,FBG,TP,SBP,LDH,Ferritin,Ca,LDL-C
0,0,168.0,1861.0,13.0,12.7,31,48.0,729,4.4,64,...,321.0,24,24,5.3,52,130.0,205,83.4,2.22,2.64
1,1,576.0,1405.0,8.0,22.3,28,47.0,1247,1.8,75,...,387.0,6,9,9.9,59,140.0,167,17.7,2.10,0.90
2,0,434.0,881.0,37.0,11.5,42,46.0,681,3.4,43,...,450.0,16,14,6.5,67,138.0,159,502.0,2.30,1.33
3,0,179.0,2665.0,31.0,14.1,32,55.0,1119,4.1,68,...,373.0,16,15,4.9,50,157.0,224,589.0,1.97,4.31
4,0,285.0,529.0,38.0,12.6,36,58.0,1065,3.8,55,...,360.0,9,16,4.9,57,174.0,200,94.6,2.29,2.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,1,185.0,35000.0,NaN,14.8,30,NaN,1192,4.0,51,...,NaN,31,25,NaN,59,139.0,372,208.0,2.16,2.30
236,0,173.0,904.0,41.0,12.0,35,NaN,969,9.2,45,...,459.0,31,37,5.2,64,123.0,218,659.0,2.16,0.87
237,1,124.0,17357.0,33.0,17.6,25,NaN,593,3.7,65,...,268.0,6,14,5.3,45,154.0,191,218.0,1.88,3.17
238,1,157.0,35000.0,10.0,21.1,35,57.0,796,2.4,74,...,NaN,11,15,NaN,62,160.0,214,264.0,2.13,NaN
239,0,451.0,2991.0,22.8,NaN,26,39.0,920,5.4,69,...,710.0,7,11,4.9,56,79.0,188,311.0,2.12,0.65

In [20]:
clean_mono_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 55 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Diabetes                        240 non-null    int64
 1   iPTH                            237 non-null    float64
 2   NT-proBNP                       237 non-null    float64
 3   TSAT                            235 non-null    float64
 4   GA                              236 non-null    float64
 5   ALB                             240 non-null    int64
 6   LVEDD                           208 non-null    float64
 7   SCR                             240 non-null    int64
 8   TB                              240 non-null    float64
 9   Age                             240 non-null    int64
 10  Cardiovascular disease history  240 non-null    int64
 11  LVEF                            208 non-null    float64
 12  Calcium phosphate binders       240 non-null    int64
 13  Left IMT                        167 non-null    float64
 14  HGB                             240 non-null    int64
 15  Gender                          240 non-null    int64
 16  UA                              240 non-null    int64
 17  UREA                            240 non-null    float64
 18  DBP                             218 non-null    float64
 19  HDL-C                           201 non-null    float64
 20  Endpoint                        240 non-null    int64
 21  Phosphate binders               240 non-null    int64
 22  Platelet                        240 non-null    int64
 23  Right IMT                       167 non-null    float64
 24  Dialysis vintage                240 non-null    int64
 25  Antiplatelet drugs              240 non-null    int64
 26  DBIL                            240 non-null    float64
 27  Hypertension                    240 non-null    int64
 28  D-Dimer                         148 non-null    float64
 29  NEUT                            240 non-null    float64
 30  cTnT                            237 non-null    float64
 31  A2MG                            240 non-null    float64
 32  Non-calcium phosphate binders   240 non-null    int64
 33  GHB                             235 non-null    float64
 34  Anemia drugs                    240 non-null    int64
 35  CRP                             239 non-null    float64
 36  BMI                             199 non-null    float64
 37  Urine volume                    219 non-null    float64
 38  Lipid-lowering drugs            240 non-null    int64
 39  APOB                            240 non-null    float64
 40  RBC                             240 non-null    float64
 41  SI                              235 non-null    float64
 42  TG                              201 non-null    float64
 43  WBC                             240 non-null    float64
 44  TCHOL                           201 non-null    float64
 45  FIB                             150 non-null    float64
 46  ALT                             240 non-null    int64
 47  AST                             240 non-null    int64
 48  FBG                             189 non-null    float64
 49  TP                              240 non-null    int64
 50  SBP                             218 non-null    float64
 51  LDH                             240 non-null    int64
 52  Ferritin                        237 non-null    float64
 53  Ca                              240 non-null    float64
 54  LDL-C                           201 non-null    float64
dtypes: float64(33), int64(22)
memory usage: 103.3 KB

In [21]:
clean_mono_data.describe()

,Diabetes,iPTH,NT-proBNP,TSAT,GA,ALB,LVEDD,SCR,TB,Age,...,FIB,ALT,AST,FBG,TP,SBP,LDH,Ferritin,Ca,LDL-C
count,240.000000,237.000000,237.000000,235.000000,236.000000,240.000000,208.000000,240.000000,240.000000,240.000000,...,150.000000,240.000000,240.000000,189.000000,240.000000,218.000000,240.000000,237.000000,240.000000,201.000000
mean,0.212500,286.400844,6748.765401,32.050213,14.111017,34.837500,48.076923,958.929167,5.212083,56.445833,...,425.440000,15.025000,15.950000,5.374603,60.450000,136.110092,205.716667,337.791983,2.236583,2.357164
std,0.409932,275.030552,10216.083077,14.580318,3.010203,5.340562,6.339345,265.240933,3.197695,11.593768,...,123.455912,9.646872,7.604612,1.588151,8.577825,20.159429,49.817438,296.744115,0.194747,0.943863
min,0.000000,14.300000,92.400000,8.000000,4.900000,18.000000,30.000000,357.000000,1.500000,24.000000,...,60.000000,3.000000,2.000000,2.300000,28.000000,78.000000,118.000000,12.900000,1.510000,0.440000
25%,0.000000,104.000000,937.000000,22.000000,12.275000,31.000000,43.000000,770.500000,3.575000,48.000000,...,344.000000,9.000000,11.000000,4.400000,55.000000,126.000000,169.000000,121.000000,2.110000,1.670000
50%,0.000000,203.000000,2088.000000,30.000000,13.600000,35.000000,48.000000,952.500000,4.600000,56.000000,...,409.500000,12.500000,15.000000,5.000000,60.000000,133.500000,200.000000,274.000000,2.240000,2.300000
75%,0.000000,379.000000,6626.000000,39.000000,15.400000,38.000000,52.000000,1120.500000,6.025000,65.250000,...,488.750000,19.000000,19.000000,5.600000,66.000000,147.000000,229.250000,461.000000,2.360000,2.980000
max,1.000000,1824.000000,35000.000000,93.000000,31.300000,48.000000,74.000000,1813.000000,35.300000,84.000000,...,800.000000,67.000000,67.000000,15.100000,85.000000,208.000000,376.000000,2000.000000,2.990000,5.260000

In [22]:
train_data, test_data = train_test_split(clean_mono_data, test_size=0.3, stratify=clean_mono_data['Endpoint'], random_state=42)

In [23]:
train_data.to_csv('../data/train.csv', index=False)
test_data.to_csv('../data/test1.csv', index=False)
clean_multi_data.to_csv('../data/test2.csv', index=False)