In [11]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [12]:
mono_data = pd.read_csv('../data/mono.csv')
multi_data  = pd.read_csv('../data/multi.csv')

In [13]:
def clean_data(data):
    to_drop = ['Number', 'Sample collection date', 'Name', 'Birth date', 'First PD date', 'End date', 'Height', 'Weight', 'CVD category']
    data = data.drop(to_drop, axis=1)
    return(data)

clean_mono_data = clean_data(mono_data)
clean_multi_data = clean_data(multi_data)

In [14]:
common_columns = list(set(clean_mono_data.columns) & set(clean_multi_data.columns))
clean_mono_data = clean_mono_data[common_columns]
clean_multi_data = clean_multi_data[common_columns]

In [15]:
clean_mono_data

,Platelet,Non-calcium phosphate binders,SCR,RBC,Ferritin,ALT,T Kt/v,TG,Age,WBC,...,APOB,P,iPTH,Dialysis vintage,NEUT,AST,TCHOL,TB,Sample number,Left IMT
0,86,0,729,2.88,83.4,24,2.00,1.10,64,2.22,...,2.17,1.43,168.0,53,66.6,24,4.52,4.4,1413,0.70
1,204,0,1247,3.30,17.7,6,1.58,4.13,75,8.44,...,2.95,2.31,576.0,56,60.7,9,3.10,1.8,1501,0.70
2,265,0,681,3.47,502.0,16,NaN,3.26,43,7.62,...,4.44,1.53,434.0,38,77.7,14,4.13,3.4,1546,NaN
3,167,0,1119,2.54,589.0,16,NaN,1.07,68,4.06,...,2.23,1.95,179.0,28,49.3,15,5.70,4.1,1581,0.95
4,313,1,1065,3.27,94.6,9,NaN,1.04,55,5.72,...,2.48,1.90,285.0,9,71.6,16,4.00,3.8,1767,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,291,0,1192,2.80,208.0,31,NaN,0.75,51,8.53,...,2.71,2.37,185.0,18,80.9,25,3.90,4.0,2320,NaN
236,115,0,969,4.13,659.0,31,0.92,2.50,45,7.71,...,23.58,2.05,173.0,33,81.1,37,2.75,9.2,2353,NaN
237,153,0,593,2.86,218.0,6,1.85,0.98,65,1.52,...,1.99,0.95,124.0,34,62.1,14,4.92,3.7,2380,0.70
238,162,0,796,3.40,264.0,11,1.35,NaN,74,3.86,...,1.51,1.66,157.0,43,76.4,15,NaN,2.4,2387,NaN
239,266,1,920,3.55,311.0,7,1.22,1.39,69,10.14,...,2.22,1.80,451.0,30,78.8,11,2.14,5.4,2432,0.70

In [16]:
clean_mono_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 58 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Platelet                        240 non-null    int64
 1   Non-calcium phosphate binders   240 non-null    int64
 2   SCR                             240 non-null    int64
 3   RBC                             240 non-null    float64
 4   Ferritin                        237 non-null    float64
 5   ALT                             240 non-null    int64
 6   T Kt/v                          181 non-null    float64
 7   TG                              201 non-null    float64
 8   Age                             240 non-null    int64
 9   WBC                             240 non-null    float64
 10  Calcium phosphate binders       240 non-null    int64
 11  BMI                             199 non-null    float64
 12  HDL-C                           201 non-null    float64
 13  Gender                          240 non-null    int64
 14  UA                              240 non-null    int64
 15  Endpoint                        240 non-null    int64
 16  DBP                             218 non-null    float64
 17  Diabetes                        240 non-null    int64
 18  Cardiovascular disease history  240 non-null    int64
 19  LVEDD                           208 non-null    float64
 20  NT-proBNP                       237 non-null    float64
 21  LVEF                            208 non-null    float64
 22  GHB                             235 non-null    float64
 23  FBG                             189 non-null    float64
 24  D-Dimer                         148 non-null    float64
 25  cTnT                            237 non-null    float64
 26  LDL-C                           201 non-null    float64
 27  FIB                             150 non-null    float64
 28  GA                              236 non-null    float64
 29  Phosphate binders               240 non-null    int64
 30  TSAT                            235 non-null    float64
 31  Right IMT                       167 non-null    float64
 32  TP                              240 non-null    int64
 33  Lipid-lowering drugs            240 non-null    int64
 34  ALB                             240 non-null    int64
 35  SI                              235 non-null    float64
 36  Urine volume                    219 non-null    float64
 37  Hypertension                    240 non-null    int64
 38  Anemia drugs                    240 non-null    int64
 39  DBIL                            240 non-null    float64
 40  HGB                             240 non-null    int64
 41  SBP                             218 non-null    float64
 42  LDH                             240 non-null    int64
 43  Antiplatelet drugs              240 non-null    int64
 44  A2MG                            240 non-null    float64
 45  CRP                             239 non-null    float64
 46  Ca                              240 non-null    float64
 47  UREA                            240 non-null    float64
 48  APOB                            240 non-null    float64
 49  P                               240 non-null    float64
 50  iPTH                            237 non-null    float64
 51  Dialysis vintage                240 non-null    int64
 52  NEUT                            240 non-null    float64
 53  AST                             240 non-null    int64
 54  TCHOL                           201 non-null    float64
 55  TB                              240 non-null    float64
 56  Sample number                   240 non-null    int64
 57  Left IMT                        167 non-null    float64
dtypes: float64(35), int64(23)
memory usage: 108.9 KB

In [17]:
clean_mono_data.describe()

,Platelet,Non-calcium phosphate binders,SCR,RBC,Ferritin,ALT,T Kt/v,TG,Age,WBC,...,APOB,P,iPTH,Dialysis vintage,NEUT,AST,TCHOL,TB,Sample number,Left IMT
count,240.000000,240.000000,240.000000,240.000000,237.000000,240.000000,181.000000,201.000000,240.000000,240.000000,...,240.000000,240.000000,237.000000,240.000000,240.000000,240.000000,201.000000,240.000000,240.000000,167.000000
mean,195.866667,0.254167,958.929167,3.485417,337.791983,15.025000,1.974033,1.756567,56.445833,6.333333,...,5.254958,1.768375,286.400844,42.429167,67.207500,15.950000,4.152388,5.212083,2101.841667,0.830539
std,66.717657,0.436302,265.240933,0.710911,296.744115,9.646872,0.664292,1.261053,11.593768,2.065154,...,17.315183,0.488673,275.030552,45.551699,10.795491,7.604612,1.081356,3.197695,156.997055,0.136969
min,40.000000,0.000000,357.000000,1.480000,12.900000,3.000000,0.780000,0.300000,24.000000,1.520000,...,0.000000,0.560000,14.300000,7.000000,0.900000,2.000000,1.650000,1.500000,1413.000000,0.500000
25%,143.000000,0.000000,770.500000,2.995000,121.000000,9.000000,1.550000,0.990000,48.000000,4.937500,...,0.357500,1.460000,104.000000,18.000000,61.075000,11.000000,3.340000,3.575000,1992.500000,0.800000
50%,191.000000,0.000000,952.500000,3.485000,274.000000,12.500000,1.820000,1.460000,56.000000,6.020000,...,1.965000,1.725000,203.000000,28.000000,68.250000,15.000000,4.090000,4.600000,2130.000000,0.800000
75%,241.750000,1.000000,1120.500000,3.932500,461.000000,19.000000,2.220000,1.970000,65.250000,7.500000,...,5.262500,2.072500,379.000000,56.000000,73.925000,19.000000,4.920000,6.025000,2222.250000,0.900000
max,424.000000,1.000000,1813.000000,5.620000,2000.000000,67.000000,5.000000,9.510000,84.000000,13.970000,...,249.340000,3.290000,1824.000000,574.000000,91.200000,67.000000,7.250000,35.300000,2432.000000,1.300000

In [18]:
train_data, test_data = train_test_split(clean_mono_data, test_size=0.3, stratify=clean_mono_data['Endpoint'], random_state=42)

In [19]:
train_data = train_data.set_index("Sample number")
test_data = test_data.set_index("Sample number")
clean_multi_data = clean_multi_data.set_index("Sample number")

In [20]:
train_data.to_csv('../data/train.csv')
test_data.to_csv('../data/test1.csv')
clean_multi_data.to_csv('../data/test2.csv')