In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
mono_data = pd.read_csv('../data/mono.csv')
multi_data  = pd.read_csv('../data/multi.csv')

In [3]:
def clean_data(data):
    to_drop = ['Number', 'Sample number', 'Sample collection date', 'Name', 'Birth date', 'First PD date', 'End date', 'Height', 'Weight', 'CVD category']
    data = data.drop(to_drop, axis=1)
    return(data)

clean_mono_data = clean_data(mono_data)
clean_multi_data = clean_data(multi_data)

In [4]:
clean_mono_data

,Endpoint,Age,Gender,Dialysis vintage,A2MG,APOB,SBP,DBP,BMI,Hypertension,...,P ccr,R kt/v,R ccr,T Kt/v,T Ccr,Urine volume,Right IMT,Left IMT,LVEF,LVEDD
0,1,64,0,53,308.67,2.17,130.0,72.0,25.1,1,...,43.56,0.37,15.31,2.00,58.87,450.0,0.70,0.70,67.0,48.0
1,1,75,0,56,1.39,2.95,140.0,80.0,28.1,1,...,37.13,0.00,0.00,1.58,37.13,0.0,0.70,0.70,63.0,47.0
2,1,43,0,38,1.35,4.44,138.0,88.0,20.8,1,...,NaN,NaN,NaN,NaN,NaN,1800.0,NaN,NaN,61.0,46.0
3,1,68,1,28,25.55,2.23,157.0,86.0,24.7,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0.95,0.95,70.0,55.0
4,1,55,1,9,8.08,2.48,174.0,108.0,25.5,1,...,NaN,NaN,NaN,NaN,NaN,1750.0,0.90,0.90,66.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,1,51,1,18,3.18,2.71,139.0,64.0,22.5,1,...,NaN,NaN,NaN,NaN,NaN,1500.0,NaN,NaN,NaN,NaN
236,1,45,1,33,13.32,23.58,123.0,88.0,26.2,1,...,40.85,0.00,0.00,0.92,40.85,0.0,NaN,NaN,NaN,NaN
237,1,65,0,34,27.49,1.99,154.0,88.0,25.3,1,...,42.53,0.31,10.55,1.85,53.08,500.0,0.70,0.70,NaN,NaN
238,1,74,0,43,66.81,1.51,160.0,85.0,24.0,1,...,36.18,0.13,4.44,1.35,40.62,200.0,NaN,NaN,49.0,57.0
239,1,69,0,30,46.29,2.22,79.0,58.0,22.4,1,...,38.01,0.02,2.84,1.22,40.85,300.0,0.80,0.70,66.0,39.0

In [5]:
clean_mono_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 62 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Endpoint                        240 non-null    int64
 1   Age                             240 non-null    int64
 2   Gender                          240 non-null    int64
 3   Dialysis vintage                240 non-null    int64
 4   A2MG                            240 non-null    float64
 5   APOB                            240 non-null    float64
 6   SBP                             218 non-null    float64
 7   DBP                             218 non-null    float64
 8   BMI                             199 non-null    float64
 9   Hypertension                    240 non-null    int64
 10  Diabetes                        240 non-null    int64
 11  Cardiovascular disease history  240 non-null    int64
 12  Antiplatelet drugs              240 non-null    int64
 13  Anemia drugs                    240 non-null    int64
 14  Lipid-lowering drugs            240 non-null    int64
 15  Phosphate binders               240 non-null    int64
 16  Calcium phosphate binders       240 non-null    int64
 17  Non-calcium phosphate binders   240 non-null    int64
 18  RBC                             240 non-null    float64
 19  HGB                             240 non-null    int64
 20  Platelet                        240 non-null    int64
 21  WBC                             240 non-null    float64
 22  NEUT                            240 non-null    float64
 23  TB                              240 non-null    float64
 24  DBIL                            240 non-null    float64
 25  TP                              240 non-null    int64
 26  ALB                             240 non-null    int64
 27  FBG                             189 non-null    float64
 28  GHB                             235 non-null    float64
 29  GA                              236 non-null    float64
 30  ALT                             240 non-null    int64
 31  AST                             240 non-null    int64
 32  LDH                             240 non-null    int64
 33  UREA                            240 non-null    float64
 34  SCR                             240 non-null    int64
 35  UA                              240 non-null    int64
 36  TCHOL                           201 non-null    float64
 37  TG                              201 non-null    float64
 38  HDL-C                           201 non-null    float64
 39  LDL-C                           201 non-null    float64
 40  Ca                              240 non-null    float64
 41  P                               240 non-null    float64
 42  SI                              235 non-null    float64
 43  TSAT                            235 non-null    float64
 44  Ferritin                        237 non-null    float64
 45  CRP                             239 non-null    float64
 46  iPTH                            237 non-null    float64
 47  NT-proBNP                       237 non-null    float64
 48  cTnT                            237 non-null    float64
 49  FIB                             150 non-null    float64
 50  D-Dimer                         148 non-null    float64
 51  P kt/V                          137 non-null    float64
 52  P ccr                           137 non-null    float64
 53  R kt/v                          137 non-null    float64
 54  R ccr                           137 non-null    float64
 55  T Kt/v                          181 non-null    float64
 56  T Ccr                           137 non-null    float64
 57  Urine volume                    219 non-null    float64
 58  Right IMT                       167 non-null    float64
 59  Left IMT                        167 non-null    float64
 60  LVEF                            208 non-null    float64
 61  LVEDD                           208 non-null    float64
dtypes: float64(40), int64(22)
memory usage: 116.4 KB

In [6]:
clean_mono_data.describe()

,Endpoint,Age,Gender,Dialysis vintage,A2MG,APOB,SBP,DBP,BMI,Hypertension,...,P ccr,R kt/v,R ccr,T Kt/v,T Ccr,Urine volume,Right IMT,Left IMT,LVEF,LVEDD
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,218.000000,218.000000,199.000000,240.0000,...,137.000000,137.000000,137.000000,181.000000,137.000000,219.000000,167.000000,167.000000,208.000000,208.000000
mean,0.220833,56.445833,0.579167,42.429167,274.129125,5.254958,136.110092,82.582569,25.836683,0.9500,...,42.773869,0.431679,20.648613,1.974033,62.855839,553.652968,0.805090,0.830539,63.211538,48.076923
std,0.415675,11.593768,0.494725,45.551699,2795.566475,17.315183,20.159429,10.963495,24.575890,0.2184,...,15.281263,0.473997,22.544667,0.664292,23.932005,541.788906,0.143497,0.136969,5.744433,6.339345
min,0.000000,24.000000,0.000000,7.000000,0.000000,0.000000,78.000000,54.000000,16.000000,0.0000,...,16.910000,0.000000,0.000000,0.780000,19.110000,0.000000,0.400000,0.500000,34.000000,30.000000
25%,0.000000,48.000000,0.000000,18.000000,2.712500,0.357500,126.000000,76.000000,21.950000,1.0000,...,33.940000,0.000000,0.240000,1.550000,45.610000,0.000000,0.800000,0.800000,61.750000,43.000000
50%,0.000000,56.000000,1.000000,28.000000,17.655000,1.965000,133.500000,82.000000,23.800000,1.0000,...,42.260000,0.260000,13.760000,1.820000,58.150000,500.000000,0.800000,0.800000,64.000000,48.000000
75%,0.000000,65.250000,1.000000,56.000000,58.450000,5.262500,147.000000,88.000000,25.850000,1.0000,...,47.560000,0.710000,34.280000,2.220000,72.700000,1000.000000,0.800000,0.900000,66.000000,52.000000
max,1.000000,84.000000,1.000000,574.000000,42563.220000,249.340000,208.000000,115.000000,367.300000,1.0000,...,132.390000,2.140000,96.170000,5.000000,167.820000,2000.000000,1.300000,1.300000,73.000000,74.000000

In [7]:
train_data, test_data = train_test_split(clean_mono_data, test_size=0.3, stratify=clean_mono_data['Endpoint'], random_state=42)

In [8]:
train_data.to_csv('../data/train.csv', index=False)
test_data.to_csv('../data/test1.csv', index=False)
clean_multi_data.to_csv('../data/test2.csv', index=False)